"""
Request/response models for the /chat endpoint.
FastAPI uses these for automatic validation, docs, and type checking.
"""

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    question: str = Field(..., min_length=1, max_length=1000, examples=[
        "How do I detect a cycle in a linked list?"
    ])
    session_id: str = Field(..., examples=["a1b2c3d4-session-1"], description=(
        "Unique ID for this conversation, e.g. a UUID generated by the frontend "
        "per browser tab/session. Used to keep chat history separate per user."
    ))


class SourceChunk(BaseModel):
    source: str
    preview: str


class ChatResponse(BaseModel):
    answer: str
    sources: list[SourceChunk]