"""
Phase 5: Conversational memory.

Simple in-memory, session-based chat history. Each session_id (generated by
the frontend, e.g. a UUID per browser tab) maps to its own message history.

NOTE: This resets when the server restarts, since it's just a Python dict.
That's fine for a portfolio demo. For production you'd swap this for Redis
or a database-backed store — worth mentioning in interviews as a known
limitation/next step.
"""

from langchain_core.chat_history import BaseChatMessageHistory
from langchain_core.messages import BaseMessage


class InMemoryHistory(BaseChatMessageHistory):
    def __init__(self):
        self.messages: list[BaseMessage] = []

    def add_messages(self, messages: list[BaseMessage]) -> None:
        self.messages.extend(messages)

    def clear(self) -> None:
        self.messages = []


# session_id -> InMemoryHistory
_session_store: dict[str, InMemoryHistory] = {}


def get_session_history(session_id: str) -> InMemoryHistory:
    if session_id not in _session_store:
        _session_store[session_id] = InMemoryHistory()
    return _session_store[session_id]


def clear_session(session_id: str) -> None:
    if session_id in _session_store:
        _session_store[session_id].clear()